// <auto-generated />
using System;
using Bid_Go_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bid_Go_Backend.Migrations
{
    [DbContext(typeof(BidGoDbContext))]
    partial class BidGoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Term")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransportRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BidId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TransportRequestId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransportRequestId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("TransportRequestId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TransportRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("BidId");

                    b.HasIndex("TransportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<float>("GrossValue")
                        .HasColumnType("float");

                    b.Property<float>("NetValue")
                        .HasColumnType("float");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<float>("Tax")
                        .HasColumnType("float");

                    b.Property<int>("TransportRequestId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TransportRequestId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<decimal>("Classification")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransportRequestId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TransportRequestId");

                    b.ToTable("Reviews");

                    b.HasDiscriminator().HasValue("Review");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.TransportRequest", b =>
                {
                    b.Property<int>("TransportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransportRequestId"));

                    b.Property<DateTime>("CollectDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destiny")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransportRequestId");

                    b.HasIndex("CompanyId");

                    b.ToTable("TransportRequests");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.ReviewCompany", b =>
                {
                    b.HasBaseType("Bid_Go_Backend.Data.Models.Review");

                    b.Property<int>("ClientSuport")
                        .HasColumnType("int");

                    b.Property<int>("ServiceQuality")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ReviewCompany");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.ReviewDriver", b =>
                {
                    b.HasBaseType("Bid_Go_Backend.Data.Models.Review");

                    b.Property<int>("Behavior")
                        .HasColumnType("int");

                    b.Property<int>("Punctuality")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ReviewDriver");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Company", b =>
                {
                    b.HasBaseType("Bid_Go_Backend.Data.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasDiscriminator().HasValue("Company");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Driver", b =>
                {
                    b.HasBaseType("Bid_Go_Backend.Data.Models.User");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasDiscriminator().HasValue("Driver");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Bid", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.TransportRequest", "TransportRequest")
                        .WithMany("Bids")
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Chat", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.TransportRequest", "TransportRequest")
                        .WithOne("Chat")
                        .HasForeignKey("Bid_Go_Backend.Data.Models.Chat", "TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Message", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Company");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Notification", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.Bid", "Bid")
                        .WithMany()
                        .HasForeignKey("BidId");

                    b.HasOne("Bid_Go_Backend.Data.Models.TransportRequest", "TransportRequest")
                        .WithMany()
                        .HasForeignKey("TransportRequestId");

                    b.HasOne("Bid_Go_Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("TransportRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Payment", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.TransportRequest", "TransportRequest")
                        .WithOne("Payment")
                        .HasForeignKey("Bid_Go_Backend.Data.Models.Payment", "TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Driver");

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Review", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bid_Go_Backend.Data.Models.TransportRequest", "TransportRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Driver");

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.TransportRequest", b =>
                {
                    b.HasOne("Bid_Go_Backend.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Bid_Go_Backend.Data.Models.TransportRequest", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
