name: .NET

on:
  push:
    branches: [ "master", "develop", "feature/*" ]
  pull_request:
    branches: [ "master", "develop", "feature/*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests with coverage
      run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults --verbosity normal


    - name: Generate coverage report
      if: success()
      run: dotnet tool install -g dotnet-reportgenerator-globaltool && reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"TestResults/CoverageReport" -reporttypes:Html


    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report-${{ matrix.os }}
        path: TestResults/CoverageReport